services:
  - type: web
    name: whatsapp-multi
    env: node
    repo: https://github.com/Danieladmsf/WhatApp-Multi
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: FIREBASE_DATABASE_URL
        value: https://cotao-online-default-rtdb.firebaseio.com/
      - key: FIREBASE_PROJECT_ID
        value: cotao-online
      - key: CLAUDE_CLI_ENABLED
        value: true
      - key: CLAUDE_CLI_COMMAND
        value: claude
      - key: CLAUDE_CLI_TIMEOUT
        value: 30000
      - key: CLAUDE_CLI_MAX_REQUESTS
        value: 10
      - key: CLAUDE_CLI_WINDOW_MS
        value: 60000
      - key: PORT
        value: 10000
      - key: WHATSAPP_HEADLESS
        value: true
      - key: WHATSAPP_SESSION_NAME
        value: whatsapp-bridge
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 10
      - key: RATE_LIMIT_WINDOW_MS
        value: 60000